name: burton.osinski
description: task-force
version: 0.0.1
author: mobtgkhj.zd3jvkdw@uctksyvb.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: burtonosinski
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2024-12-20 20:34:25'
pipelines:
  pipelines/Mr__Pauline_FritschBen_DownEffie_Schoen:
    name: Mr__Pauline_FritschBen_DownEffie_Schoen
    description: null
    author: mobtgkhj.zd3jvkdw@uctksyvb.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-12-20 20:34:25'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-12-20 20:34:25'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-12-20T20:34:25.646734Z'
  name: plibMaven
  version: 8.8.0-SNAPSHOT
  id: '1074303435'
  createdAt: '2024-12-20T20:34:25.646734Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
